version: "2.3"

services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 7000:80
        volumes:
            - ./docker/nginx/default:/etc/nginx/conf.d/default.conf:ro
            - /tmp/webroot:/usr/share/nginx/html
        networks:
            - rasp4php
        links:
            - rasp4php7

    rasp4php7:
        build: ./docker/rasp4php
        container_name: rasp4php7
        networks:
            - rasp4php
        volumes:
            - /tmp/webroot:/usr/share/nginx/html
        expose:
            - 9000
        cap_add:
            - SYS_PTRACE

networks:
    rasp4php: