version: "2.3"

services:
    nginx:
        image: nginx
        container_name: rasp4php_nginx
        ports:
            - 7777:80
        volumes:
            - ./docker/nginx/default:/etc/nginx/conf.d/default.conf:ro
            - rasp4php_webroot:/usr/share/nginx/html
        networks:
            - rasp4php
        links:
            - rasp4php7

    rasp4php7:
        build: ./docker/rasp4php
        container_name: rasp4php7
        networks:
            - rasp4php
        volumes:
            - rasp4php_webroot:/usr/share/nginx/html
        expose:
            - 9000
        cap_add:
            - SYS_PTRACE

networks:
    rasp4php:

volumes:
    rasp4php_webroot: